### ISSUE TITLE
Nothing happens when I click on the connect button

### ISSUE THREAD

**Issue by rajesh1158** [sreesharp/react-native-twilio-video#2]
There is a 'connect' button inside the modal popup. When I click on that, nothing happens. Is the remote preview only visible if there is a remote participant available? Currently I am seeing a screenshot of my mobile (with launcher icons) in the preview, and below that I see my own live camera feed (front camera). The modal popup remains open and does not close. Please help.

**Comment by rajesh1158** [comment]
I added an event handler for video track and found that the video track map size is 0 because unable to get the video track. What is to be done here? Any pointers?

**Comment by sreesharp** [comment]
Hey Rajesh,  Please feel to fork and fix the issue. It was an experimental wrapper, and I am not putting any efforts on this due to other priority items.
